<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="surfacearea" nsURI="us.coastalhacking.semiotics.model.surfacearea"
    nsPrefix="surfacearea">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="editDirectory" value="/us.coastalhacking.semiotics.model.surfacearea.edit/src-gen"/>
    <details key="forceOverwrite" value="true"/>
    <details key="basePackage" value="us.coastalhacking.semiotics.model"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SurfaceAreaGroup" eSuperTypes="../../us.coastalhacking.semiotics.model.base/model/base.ecore#//Nameable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="surfaceAreas" upperBound="-1"
        eType="#//SurfaceArea" containment="true" resolveProxies="false" eOpposite="#//SurfaceArea/surfaceAreaGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SurfaceArea" eSuperTypes="../../us.coastalhacking.semiotics.model.base/model/base.ecore#//Reviewable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="surfaceAreaGroup" eType="#//SurfaceAreaGroup"
        eOpposite="#//SurfaceAreaGroup/surfaceAreas"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controls" upperBound="-1"
        eType="ecore:EClass ../../us.coastalhacking.semiotics.model.control/model/control.ecore#//Control"/>
  </eClassifiers>
</ecore:EPackage>
