<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="data" nsURI="us.coastalhacking.semiotics.model.data" nsPrefix="data">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="editDirectory" value="/us.coastalhacking.semiotics.model.data.edit/src-gen"/>
    <details key="forceOverwrite" value="true"/>
    <details key="basePackage" value="us.coastalhacking.semiotics.model"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Data" eSuperTypes="../../us.coastalhacking.semiotics.model.base/model/base.ecore#//Nameable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="snippets" upperBound="-1"
        eType="#//Snippet" containment="true" resolveProxies="false" eOpposite="#//Snippet/data"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataGroup" eType="#//DataGroup"
        eOpposite="#//DataGroup/data"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataGroup" eSuperTypes="../../us.coastalhacking.semiotics.model.base/model/base.ecore#//Nameable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="#//Data"
        containment="true" resolveProxies="false" eOpposite="#//Data/dataGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Snippet" eSuperTypes="../../us.coastalhacking.semiotics.model.base/model/base.ecore#//Provable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" eType="#//Data" eOpposite="#//Data/snippets"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="row" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="File" eSuperTypes="#//Data">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullPath" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Request" eSuperTypes="#//Data">
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" eType="#//Response"
        eOpposite="#//Response/request"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Response" eSuperTypes="#//Data">
    <eStructuralFeatures xsi:type="ecore:EReference" name="request" eType="#//Request"
        eOpposite="#//Request/response"/>
  </eClassifiers>
</ecore:EPackage>
