<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="control" nsURI="us.coastalhacking.semiotics.model.control" nsPrefix="control">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="editDirectory" value="/us.coastalhacking.semiotics.model.control.edit/src-gen"/>
    <details key="editorDirectory" value="/us.coastalhacking.semiotics.model.control.editor/src-gen"/>
    <details key="forceOverwrite" value="true"/>
    <details key="basePackage" value="us.coastalhacking.semiotics.model"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ControlGroup" eSuperTypes="../../us.coastalhacking.semiotics.model.base/model/base.ecore#//Nameable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="labelFeature" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controls" upperBound="-1"
        eType="#//Control" containment="true" resolveProxies="false" eOpposite="#//Control/controlGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Control" eSuperTypes="../../us.coastalhacking.semiotics.model.base/model/base.ecore#//Reviewable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlGroup" eType="#//ControlGroup"
        eOpposite="#//ControlGroup/controls"/>
  </eClassifiers>
</ecore:EPackage>
